apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerance1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
    - key: "name"
      operator: "Equal"
      value: "sri"
      effect: "NoExecute"